name: Deploy Branch to GitHub Pages

# when the current branch makes a PR, this workflow will deploy the changes to github pages so that the changes can be tested in a live environment

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: actions/deploy-pages@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
          message: "Deploying to GitHub Pages"
          skip-build: trueS




