name: Deploy Branch to GitHub Pages

# when the current branch makes a PR, this workflow will deploy the changes to github pages so that the changes can be tested in a live environment

on:
  pull_request:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: read
  pages: write
  id-token: write

jobs:
  build-attempt-to-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./shesha-reactjs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        id: build
        run: npm run build

      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
          message: "Deploying to GitHub Pages"
          skip-build: trueS




